### ISSUE TITLE
Doesn't start on jekyll 2.5.3

### ISSUE THREAD

**Issue by bogdanr** [kippt/jekyll-incorporated#33]
When I try to serve this on Jekyll 2.5.3 with Ruby 1.9.3 I get the following error message:

```
nimblex:~/jekyll-incorporated-master# jekyll serve
/usr/lib64/ruby/gems/1.9.1/gems/psych-2.0.15/lib/psych.rb:226: warning: already initialized constant VERSION
/usr/lib64/ruby/gems/1.9.1/gems/psych-2.0.15/lib/psych.rb:229: warning: already initialized constant LIBYAML_VERSION
Configuration file: /root/jekyll-incorporated-master/_config.yml
/usr/lib64/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- jekyll-assets (LoadError)
        from /usr/lib64/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /root/jekyll-incorporated-master/_plugins/_ext.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib64/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/lib64/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /usr/bin/jekyll:23:in `load'
        from /usr/bin/jekyll:23:in `<main>'
```

**Comment by bogdanr** [comment]
The fix for that error is:
`gem install jekyll-assets rake sass uglifier github-pages maruku`
